apiVersion: v1
kind: Service
metadata:
  name: btcbot-inference-service
  namespace: btcbot
  labels:
    app: btcbot-inference
spec:
  type: ClusterIP
  selector:
    app: btcbot-inference
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
