apiVersion: apps/v1
kind: Deployment
metadata:
  name: btcbot-live-trader
  namespace: btcbot
  labels:
    app: btcbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btcbot-trader
  template:
    metadata:
      labels:
        app: btcbot-trader
    spec:
      serviceAccountName: btcbot-inference-sa  # Usar la misma SA para acceso a GCS
      containers:
      - name: btcbot-runner
        image: europe-southwest1-docker.pkg.dev/lofty-complex-460416-r6/lofty-complex-460416-r6-repo/btcbot-cpu:latest
        command: ["python", "scripts/run_live_trader.py"]
        args: ["--config_path", "src/config.yaml", "--use_internal_service"]
        env:
        # --- Variables de Configuración de GCP ---
        - name: GCP_PROJECT_ID
          value: "lofty-complex-460416-r6"
        - name: GCS_BUCKET_NAME
          value: "lofty-complex-460416-r6"
        - name: GCP_REGION
          value: "europe-southwest1"

        # --- Variables de Configuración del Bot ---
        - name: LIVE_TRADING_MODE # "TESTNET" o "REAL"
          value: "TESTNET"

        # --- Nombres de los Secretos en Google Cloud Secret Manager ---
        - name: SECRET_NAME_BINANCE_API_KEY_FUTURES
          value: "BINANCE_API_KEY_FUTURES"
        - name: SECRET_NAME_BINANCE_API_SECRET_FUTURES
          value: "BINANCE_API_SECRET_FUTURES"
        - name: SECRET_NAME_TESTNET_BINANCE_API_KEY_FUTURES
          value: "TESTNET_BINANCE_API_KEY_FUTURES"
        - name: SECRET_NAME_TESTNET_BINANCE_API_SECRET_FUTURES
          value: "TESTNET_BINANCE_API_SECRET_FUTURES"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
