
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-southwest1-docker.pkg.dev/btcbot276299/btcbot-docker-repo/btcbot-training:latest', '-f', 'Dockerfile', '.']
images: ['europe-southwest1-docker.pkg.dev/btcbot276299/btcbot-docker-repo/btcbot-training:latest']
    