# Configuración declarativa para el bot de trading en vivo (worker pool)

apiVersion: run.googleapis.com/v1
kind: WorkerPool
metadata:
  name: btcbot-live-worker
spec:
  template:
    spec:
      serviceAccountName: btcbot-live-runner@btcbot-2762.iam.gserviceaccount.com
      containers:
        - image: europe-southwest1-docker.pkg.dev/btcbot-2762/btcbotrepo/btcbot-train-gpu:latest
          command: ["python"]
          args:
            - "live.py"
            - "--run-id=ID_DEL_RUN_A_USAR"
            - "--mode=testnet"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"

# gcloud beta run worker-pools replace cloudrun.yaml --region=europe-southwest1

# gcloud beta run worker-pools delete btcbot-live-worker --region=europe-southwest1