FROM python:3.11.6-slim

# Instalación de dependencias base
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    wget \
    ca-certificates \
    libglib2.0-0 \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Directorio de trabajo
WORKDIR /app

# Actualizar pip a la última versión
RUN pip install --no-cache-dir --upgrade pip

# Copia de archivos de requisitos e instalación de dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Instalación de PyTorch con soporte para CUDA 11.8
RUN pip install --no-cache-dir torch==2.2.2+cu118 torchvision==0.17.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118 --timeout 300

# Instalación del cliente de Google Cloud
RUN pip install --no-cache-dir google-cloud-storage google-cloud-secret-manager --timeout 300

# Copia del código fuente del proyecto
COPY . .

# Copia el archivo .env.example como referencia
# COPY .env.example /app/.env-example

# Creación de directorios necesarios
RUN mkdir -p logs/training logs/eval models/best_model

# Variables de entorno
ENV PYTHONPATH=/app
ENV CUDA_VISIBLE_DEVICES=0
ENV TF_FORCE_GPU_ALLOW_GROWTH=true

# Variables de entorno para Google Cloud (configurar al ejecutar el contenedor)
ENV GCP_PROJECT_ID="lofty-complex-460416-r6"
ENV GCS_BUCKET_NAME="lofty-complex-460416-r6"
ENV GCP_REGION="europe-southwest1"
ENV USE_CLOUD_LOGGING="true"
# Para la cuenta REAL de Binance Futures
ENV SECRET_NAME_BINANCE_API_KEY_FUTURES="BINANCE_API_KEY_FUTURES"
ENV SECRET_NAME_BINANCE_API_SECRET_FUTURES="BINANCE_API_SECRET_FUTURES"

# Para la cuenta TESTNET de Binance Futures
ENV SECRET_NAME_TESTNET_BINANCE_API_KEY_FUTURES="TESTNET_BINANCE_API_KEY_FUTURES"
ENV SECRET_NAME_TESTNET_BINANCE_API_SECRET_FUTURES="TESTNET_BINANCE_API_SECRET_FUTURES"

# Live Trading Mode: TESTNET o REAL
# Esta variable determinará qué conjunto de NOMBRES de secretos se utilizan.
ENV LIVE_TRADING_MODE="TESTNET"
# Puede ser "TESTNET" o "REAL"

# IMPORTANTE: Exponer el puerto 8080 que Vertex AI utilizará
EXPOSE 8080

# No se configura GOOGLE_APPLICATION_CREDENTIALS para permitir ADC
# La autenticación se realizará mediante Workload Identity o
# configurando credenciales en tiempo de ejecución
ENTRYPOINT ["python"]
