FROM python:3.11.6-slim

# Instalación de dependencias base
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Directorio de trabajo
WORKDIR /app

# Actualizar pip a la última versión
RUN pip install --no-cache-dir --upgrade pip

# Copia de archivos de requisitos e instalación de dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --timeout 300

# Instalación de PyTorch versión CPU
RUN pip install --no-cache-dir torch==2.2.2+cpu torchvision==0.17.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu --timeout 300

# Instalación del cliente de Google Cloud
RUN pip install --no-cache-dir google-cloud-storage google-cloud-secret-manager

# Copia del código fuente del proyecto
COPY . .

# Copia el archivo .env.example como referencia
# COPY .env.example /app/.env-example

# Creación de directorios necesarios
RUN mkdir -p logs/training logs/eval models/best_model

# Variables de entorno
ENV PYTHONPATH=/app

# Variables de entorno para Google Cloud (configurar al ejecutar el contenedor)
ENV GCP_PROJECT_ID="bitcoin-460320"
ENV GCS_BUCKET_NAME="bitcoin-460320_data"
ENV GCP_REGION="europe-southwest1"

# No se configura GOOGLE_APPLICATION_CREDENTIALS para permitir ADC
# La autenticación se realizará mediante Workload Identity o
# configurando credenciales en tiempo de ejecución
