apiVersion: v1
kind: ConfigMap
metadata:
  name: btcbot-env-vars
  namespace: btcbot
data:
  GCP_PROJECT_ID: "lofty-complex-460416-r6"
  GCS_BUCKET_NAME: "lofty-complex-460416-r6"
  GCP_REGION: "europe-southwest1"
  BIGQUERY_LOG_DATASET_ID: "btcbot_logs"
  LIVE_TRADING_MODE: "false"  # Cambiar a "true" para trading real
