apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-acquisition-cronjob
  namespace: btcbot
spec:
  schedule: "0 0 * * 6"  # Cada sábado a las 00:00 UTC
  timeZone: "UTC"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: btcbot-ksa
          restartPolicy: OnFailure
          containers:
          - name: data-acquisition
            image: europe-southwest1-docker.pkg.dev/lofty-complex-460416-r6/lofty-complex-460416-r6-repo/btcbot-cpu:latest
            command: ["python", "scripts/download_data.py"]
            envFrom:
            - configMapRef:
                name: btcbot-env-vars
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
          nodeSelector:
            kubernetes.io/arch: amd64
