apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job-autopilot
  namespace: btcbot
spec:
  template:
    spec:
      serviceAccountName: btcbot-ksa
      restartPolicy: OnFailure
      containers:
      - name: model-training
        image: europe-southwest1-docker.pkg.dev/lofty-complex-460416-r6/lofty-complex-460416-r6-repo/btcbot-cpu:latest
        command: ["python", "scripts/train_rl_agent.py"]
        envFrom:
        - configMapRef:
            name: btcbot-env-vars
        env:
        - name: FORCE_CPU_TRAINING
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          # Autopilot ajustará automáticamente los limits
      nodeSelector:
        kubernetes.io/arch: amd64
