data_paths:
  raw: "data/raw"
  processed: "data/processed"

binance_api:
  futures_base_url: "https://fapi.binance.com"
  request_limit_per_call: 1000
  request_delay_seconds: 0.5
  retry_attempts: 5
  retry_delay_seconds: 60

data_acquisition_defaults:
  symbol: "BTCUSDT"
  interval: "1h"
  historical_start_date: "2020-01-01"
