apiVersion: apps/v1
kind: Deployment
metadata:
  name: btcbot-live-trader
  namespace: btcbot
  labels:
    app: btcbot-live-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btcbot-live-trader
  template:
    metadata:
      labels:
        app: btcbot-live-trader
      annotations:
        # Cloud NAT para asegurar que usemos nuestra IP estática
        cloud.google.com/network-tier: "Premium"
    spec:
      serviceAccountName: btcbot-ksa  # Usa la KSA para Workload Identity
      containers:
      - name: btcbot-live-trader
        image: europe-southwest1-docker.pkg.dev/lofty-complex-460416-r6/lofty-complex-460416-r6-repo/btcbot-cpu:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            touch /tmp/healthy /tmp/ready
            python scripts/run_live_trader.py --modelpath models/sac_transformer_trading_agent/best_model/best_model.zip
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        envFrom:
        - configMapRef:
            name: btcbot-env-vars  # Usa el ConfigMap existente
        env:
        - name: LIVE_TRADING_MODE
          value: "true"  # Sobreescribe el valor del ConfigMap para habilitar modo de trading en vivo
        # Configuración para la sonda de salud
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import os; exit(0 if os.path.exists('/tmp/healthy') else 1)"
          initialDelaySeconds: 120
          periodSeconds: 60
        # Añadimos una sonda de preparación
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import os; exit(0 if os.path.exists('/tmp/ready') else 1)"
          initialDelaySeconds: 30
          periodSeconds: 30
